apiVersion: apps/v1
kind: Deployment
metadata:
  name: trekking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trekking-app
  template:
    metadata:
      labels:
        app: trekking-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
        - name: artifact-registry-secret
      containers:
        - name: my-app-repo
          image: australia-southeast2-docker.pkg.dev/sit737-25t1-katuwal-ch-1ae0a33/my-app-repo/trekking-web-server:v1
          env:
            - name: MONGO_USER
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: username
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
            - name: MONGO_URI
              value: |
                mongodb://$(MONGO_USER):$(MONGO_PASS)@mongodb.default.svc.cluster.local:27017/trekkingDB?authSource=trekkingDB&directConnection=true
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
