apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - name: mongodb
      port: 27017        # in-cluster port you’ll use in your URI
      targetPort: 27017  # Pod’s real listening port
  clusterIP: None
  selector:
    app: mongodb
