version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app
    container_name: trekking-web-server
    image: anushakatuwal99/trekking-web-server:v1
    restart: always
    ports:
      - "3000:3000"
    command: node app.js
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s