apiVersion: v1
kind: Service
metadata:
  name: calculator-service-v1
spec:
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 80           # The port clients will use to access the service
      targetPort: 3000    # The port your container listens on 3000
  type: NodePort         # So you can access it via localhost:<nodePort>