apiVersion: v1
kind: Pod
metadata:
  name: my-pod-v2
  labels:
    run: my-pod-v2
spec:
  containers:
  - image: anushakatuwal99/calculator-web-server:v2
    name: calculator-web-server
    ports:
    - containerPort: 3090
  dnsPolicy: ClusterFirst
  restartPolicy: Always