apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploymentv2
  labels:
    app: myapp
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: mynode
        image: anushakatuwal99/calculator-web-server:v2
        ports:
        - containerPort: 3090