apiVersion: v1
kind: Service
metadata:
  name: mongodb             # this is the DNS name your app will use
spec:
  selector:
    app: mongodb            # must match your MongoDB pod label
  ports:
    - port: 27017           # in-cluster MongoDB port
      targetPort: 27017
  type: ClusterIP           # only accessible from inside the cluster